const getPlaceholder = (name) => `https://placehold.co/400x300/4a0000/FFD700?text=${name}+Mudra&font=lora`;

const asamyuthaHastas = [
    { name: "Pataka", image: "images/pdf_extract/img_p1_1.jpeg", placement: "All fingers straight and held together.", math: ["Parallel lines: All fingers are held tightly parallel to each other.", "Straight angles: The fingers form a flat 180° plane with the palm.", "Reflection symmetry: Creates a perfectly balanced, symmetrical shape."], nonMath: false },
    { name: "Tripataka", image: "images/pdf_extract/img_p2_1.jpeg", placement: "Third finger bent, others straight.", math: ["Angle variation: The bent ring finger breaks the flat plane, creating a distinct 90° angle.", "Geometric transformation: A simple geometric shift from the Pataka state."], nonMath: false },
    { name: "Ardhapataka", image: "images/pdf_extract/img_p3_1.jpeg", placement: "Little finger also bent.", math: ["Asymmetry: Introduces unequal visual weight between the extended and bent fingers.", "Partial transformation: Shows a step-by-step reduction of the surface area."], nonMath: false },
    { name: "Kartarimukha", image: "images/pdf_extract/img_p4_1.jpeg", placement: "Index and middle fingers apart like scissors.", math: ["V-shaped angles: The index and middle fingers form a clear acute angle (V-shape).", "Intersecting lines: Simulates the intersection point of two crossing lines."], nonMath: false },
    { name: "Mayura", image: "images/pdf_extract/img_p5_1.jpeg", placement: "Ring finger meets thumb, others straight.", math: ["Curves: The ring finger and thumb create a perfect arc.", "Circular geometry: Forms a closed circular loop amidst straight lines."], nonMath: false },
    { name: "Ardhachandra", image: "images/pdf_extract/img_p6_1.jpeg", placement: "Thumb and fingers form a half moon.", math: ["Semicircle geometry: The hand arcs perfectly to represent a 180° semi-circle."], nonMath: false },
    { name: "Arala", image: "images/pdf_extract/img_p7_1.jpeg", placement: "Index finger bent, others straight.", math: ["Directional bending: The index finger creates a sharp downward vector.", "Curved angle: Demonstrates a curved geometry breaking straight parallel lines."], nonMath: false },
    { name: "Shukatunda", image: "images/pdf_extract/img_p8_1.jpeg", placement: "Index and ring fingers bent.", math: ["Multiple angle formation: Creates two distinct bent angles separated by straight fingers.", "Complex geometry: Demonstrates non-contiguous symmetry."], nonMath: false },
    { name: "Mushti", image: "images/pdf_extract/img_p9_1.jpeg", placement: "All fingers closed into a fist, thumb over them.", math: ["Compact geometry: Reduces the hand to its minimal geometric volume.", "Spherical shape: Simulates a dense, rounded 3D object."], nonMath: false },
    { name: "Shikhara", image: "images/pdf_extract/img_p10_1.jpeg", placement: "Fist with thumb pointing straight up.", math: ["Vertical axis representation: The thumb acts as a strict Y-axis pointing upwards.", "Perpendicular lines: The thumb sits at a 90° angle to the curled fingers."], nonMath: false },
    { name: "Kapittha", image: "images/pdf_extract/img_p11_1.jpeg", placement: "Thumb tucked under index finger in a fist.", math: ["Point intersections: The thumb and index finger intersect at a precise coordinate.", "Enclosed volume: Creates a tightly enclosed geometric space."], nonMath: false },
    { name: "Katakamukha", image: "images/pdf_extract/img_p12_1.jpeg", placement: "Index, middle, and thumb joined together.", math: ["Triangle formation: The three joined fingers create a 3D triangular pyramid.", "Focal convergence: Multiple points converging to a single coordinate."], nonMath: false },
    { name: "Suchi", image: "images/pdf_extract/img_p13_1.jpeg", placement: "Index finger pointing straight up.", math: ["Rays and vectors: Represents a strict, unidirectional mathematical vector.", "Line geometry: Acts as a single straight line extending into space."], nonMath: true, nonMathDesc: "Often represents the supreme being, focus, or a specific object, deeply rooted in storytelling." },
    { name: "Chandrakala", image: "images/pdf_extract/img_p14_1.jpeg", placement: "Thumb and index finger open to form a crescent.", math: ["Angular spread: Creates a wide, measurable angle between two digits.", "Crescent arc: Simulates the geometric curve of a crescent moon."], nonMath: true, nonMathDesc: "Used to depict the moon or face, focusing on aesthetic beauty and emotion." },
    { name: "Padmakosha", image: "images/pdf_extract/img_p15_1.jpeg", placement: "Fingers slightly curved, resembling a lotus bud.", math: ["3D geometry and volume: Forms a hollow hemisphere with internal volume.", "Spatial curvature: All fingers curve equally toward a central focal point."], nonMath: false },
    { name: "Sarpashirsha", image: "images/pdf_extract/img_p16_1.jpeg", placement: "Pataka hand with fingers slightly hollowed.", math: ["Curved arcs: The palm creates a concave geometric surface.", "Surface tension: Demonstrates a curved plane rather than a flat one."], nonMath: false },
    { name: "Mrigashirsha", image: "images/pdf_extract/img_p17_1.jpeg", placement: "Thumb and little finger extended, others bent.", math: ["Pattern geometry: Creates a U-shaped geometric pattern.", "Parallel extension: The two outer fingers extend in parallel opposite directions."], nonMath: false },
    { name: "Simhamukha", image: "images/pdf_extract/img_p18_1.jpeg", placement: "Middle and ring fingers joined to thumb.", math: ["Composite geometry: Combines a circular loop in the center with straight vectors on the sides.", "Symmetrical balance: Outer fingers balance the inner loop perfectly."], nonMath: false },
    { name: "Kangula", image: "images/pdf_extract/img_p19_1.jpeg", placement: "Ring finger curved inside, others extended.", math: ["Angle differentiation: One digit curves inward while others maintain an outward vector.", "Spatial depth: Adds a Z-axis element to a mostly flat hand."], nonMath: false },
    { name: "Alapadma", image: "images/pdf_extract/img_p20_1.jpeg", placement: "Fingers fully opened and turned outward.", math: ["Radial symmetry: Fingers spread outward from the palm like rays from a center point.", "Circular spacing: The fingers create a mathematically perfect fan shape."], nonMath: false },
    { name: "Chatura", image: "images/pdf_extract/img_p21_1.jpeg", placement: "Thumb tucked under fingers.", math: ["Non-linear geometry: Breaks the flat plane into an irregular step shape.", "Square proportion: Can be used to symbolize a square or four-sided object."], nonMath: false },
    { name: "Bhramara", image: "images/pdf_extract/img_p22_1.jpeg", placement: "Thumb and middle finger joined, index bent.", math: ["Circular loops: The middle finger and thumb create a perfect circle.", "Complex intersection: Intersecting curves mimicking flight paths."], nonMath: true, nonMathDesc: "Depicts a bee, focusing on the emotion of hovering and attraction." },
    { name: "Hamsasya", image: "images/pdf_extract/img_p23_1.jpeg", placement: "Thumb and index finger joined, others extended.", math: ["Precision point geometry: A microscopic focal point where two fingers perfectly meet.", "Golden ratio: The proportions often mimic the fibonacci spiral of a swan."], nonMath: true, nonMathDesc: "Represents tying a knot, pearls, or certainty, deeply symbolic." },
    { name: "Hamsapaksha", image: "images/pdf_extract/img_p24_1.jpeg", placement: "Little finger extended from a flat hand.", math: ["Wave patterns: Mimics the aerodynamic curvature of a wing.", "Vector deviation: One line breaks away from the parallel group."], nonMath: false },
    { name: "Sandamsha", image: "images/pdf_extract/img_p25_1.jpeg", placement: "Opening and closing of fingers and thumb.", math: ["Motion sequences: Represents kinematic geometry and rhythmic oscillation.", "Variable angles: The angle changes continuously over time."], nonMath: true, nonMathDesc: "Represents grasping or a heartbeat, full of emotional nuance." },
    { name: "Mukula", image: "images/pdf_extract/img_p26_1.jpeg", placement: "All five fingers brought together at the tips.", math: ["Geometric convergence: All 5 endpoints perfectly converge to a single spatial coordinate.", "Cone geometry: Forms a 3D conical structure."], nonMath: true, nonMathDesc: "Represents eating, the god of love, or a blooming flower, highly evocative." },
    { name: "Tamrachuda", image: "images/pdf_extract/img_p27_1.jpeg", placement: "Index finger curved, others joined to thumb.", math: ["Irregular geometry: Combines a hook shape with a closed loop.", "Asymmetrical balance: Balances complex curves on one side with mass on the other."], nonMath: false },
    { name: "Trishula", image: "images/pdf_extract/img_p28_1.jpeg", placement: "Thumb and little finger joined, middle three extended.", math: ["Parallel grouped lines: The three central fingers form three perfectly parallel vertical lines.", "Trident symmetry: Perfect bilateral symmetry across the middle finger axis."], nonMath: false }
];

const samyuthaHastas = [
    { name: "Anjali", image: "images/pdf_extract/samyutha_p1_1.jpeg", placement: "Two Pataka hands joined palm to palm.", math: ["Bilateral Symmetry: The left side perfectly mirrors the right side.", "Mirror Symmetry: The hands act as perfect geometric reflections of one another.", "Equal Proportion: Volume and mass are equally distributed."], nonMath: true, nonMathDesc: "The ultimate gesture of respect, prayer, and salutation to God or Guru." },
    { name: "Kapota", image: "images/pdf_extract/samyutha_p2_1.jpeg", placement: "Anjali hands with palms slightly hollowed.", math: ["Symmetrical Balance: Inner empty volume perfectly balanced between two hands.", "Geometric Uniformity: A convex exterior hiding a concave interior."], nonMath: true, nonMathDesc: "Represents a pigeon, but used to show respectful acceptance or coldness." },
    { name: "Karkata", image: "images/pdf_extract/samyutha_p3_1.jpeg", placement: "Fingers interlocked tightly.", math: ["Interlocking Pattern: Represents interwoven geometric grids.", "Spatial Arrangement: Alternating sequences of left and right fingers."], nonMath: true, nonMathDesc: "Often represents anxiety, a crowd, or blowing a conch." },
    { name: "Swastika", image: "images/pdf_extract/samyutha_p4_1.jpeg", placement: "Two Pataka hands crossed at wrists.", math: ["Cross Symmetry: Creates four distinct quadrants via intersection.", "Intersecting Angles: The wrists intersect at an exact angle, creating an X geometry."], nonMath: false },
    { name: "Dola", image: "images/pdf_extract/samyutha_p5_1.jpeg", placement: "Pataka hands relaxed alongside the thighs.", math: ["Parallel Lines: The arms create two parallel vertical vectors along the body.", "Vertical Alignment: Strict alignment along the Y-axis of the dancer."], nonMath: false },
    { name: "Pushpaputa", image: "images/pdf_extract/samyutha_p6_1.jpeg", placement: "Sarpashirsha hands joined at the sides.", math: ["Curved Geometry: The two hands form a continuous parabolic bowl.", "Semi-Circular Formation: Creates a perfect half-sphere to hold objects."], nonMath: false },
    { name: "Utsanga", image: "images/pdf_extract/samyutha_p7_1.jpeg", placement: "Hands crossed and touching opposite shoulders.", math: ["Angular Balance: Creates a closed geometric loop across the chest.", "Symmetrical Positioning: X-axis symmetry maintained across the torso."], nonMath: false },
    { name: "Shivalinga", image: "images/pdf_extract/samyutha_p8_1.jpeg", placement: "Left hand as Ardhachandra, Right as Shikhara on it.", math: ["Cylindrical Structure: The right fist forms a cylinder resting on a flat plane.", "Central Alignment: The vertical axis is perfectly centered on the horizontal base."], nonMath: true, nonMathDesc: "Symbolizes Lord Shiva. Purely spiritual and deeply mythological." },
    { name: "Katakavardhana", image: "images/pdf_extract/samyutha_p9_1.jpeg", placement: "Two Katakamukha hands crossed at wrists.", math: ["Angular Symmetry: Intersecting triangular formations.", "Balanced Proportions: Weight is evenly distributed across the intersection."], nonMath: false },
    { name: "Kartariswastika", image: "images/pdf_extract/samyutha_p10_1.jpeg", placement: "Two Kartarimukha hands crossed at wrists.", math: ["Crossing Angles: Multiple acute angles crossing over each other.", "X-Shaped Geometry: Creates a fractal-like X shape within an X shape."], nonMath: false },
    { name: "Sakata", image: "images/pdf_extract/samyutha_p11_1.jpeg", placement: "Bhramara hands with thumb and middle fingers projected.", math: ["Structural Symmetry: Mirrors complex loop geometries on both sides.", "Balanced Shape: Complex external vectors balancing internal closed loops."], nonMath: false },
    { name: "Sankha", image: "images/pdf_extract/samyutha_p12_1.jpeg", placement: "Thumb of left hand clasped in right hand.", math: ["Spiral Formation: The hands wrap around each other simulating a spiral or helix.", "Circular Curvature: Represents the organic geometry of a conch shell."], nonMath: false },
    { name: "Chakra", image: "images/pdf_extract/samyutha_p13_1.jpeg", placement: "Palms of two Ardhachandra hands placed across.", math: ["Circular Geometry: The two half-moons combine to form a full geometric circle.", "Rotational Symmetry: The shape remains identical if rotated 180 degrees."], nonMath: false },
    { name: "Samputa", image: "images/pdf_extract/samyutha_p14_1.jpeg", placement: "Fingers of Chakra hands bent inwards.", math: ["Closed Geometric Form: Represents a fully enclosed, hollow 3D sphere.", "Symmetrical Enclosure: Perfectly contained internal volume."], nonMath: false },
    { name: "Pasa", image: "images/pdf_extract/samyutha_p15_1.jpeg", placement: "Index fingers of two Suchi hands interlocked.", math: ["Loop Formation: Two rigid vectors linked by a flexible loop.", "Circular Connection: Demonstrates mathematical linking of two distinct sets."], nonMath: true, nonMathDesc: "Represents enmity, bonds, or chains. Highly emotional and narrative-driven." },
    { name: "Keelaka", image: "images/pdf_extract/samyutha_p16_1.jpeg", placement: "Little fingers interlocked.", math: ["Connected Symmetry: Similar to Pasa but using smaller digits, forming a micro-loop.", "Angular Coordination: The hands hinge mathematically around the interlocked point."], nonMath: false },
    { name: "Matsya", image: "images/pdf_extract/samyutha_p17_1.jpeg", placement: "One palm over the other, thumbs extended.", math: ["Bilateral Symmetry: The extended thumbs mirror each other exactly.", "Streamlined Shape: Mimics aerodynamic and fluid dynamics geometry."], nonMath: true, nonMathDesc: "Depicts the Matsya (fish) avatar of Vishnu. Mythological context." },
    { name: "Kurma", image: "images/pdf_extract/samyutha_p18_1.jpeg", placement: "Ends of fingers of Chakra bent, thumbs crossed.", math: ["Oval Geometry: Forms an elliptical geometric dome.", "Layered Structure: Demonstrates stacked, concentric geometric planes."], nonMath: false },
    { name: "Varaha", image: "images/pdf_extract/samyutha_p19_1.jpeg", placement: "Two Mrigashirsha hands placed one over the other.", math: ["Curved Projection: Extended fingers create dual parallel vectors.", "Geometric Extension: A linear projection stemming from a solid base."], nonMath: false },
    { name: "Garuda", image: "images/pdf_extract/samyutha_p20_1.jpeg", placement: "Two Ardhachandra hands held with thumbs interlocked.", math: ["Wing Symmetry: Beautiful radial expansion mirroring bird wings.", "Horizontal Expansion: Maximizes surface area along the X-axis."], nonMath: false },
    { name: "Nagabandha", image: "images/pdf_extract/samyutha_p21_1.jpeg", placement: "Two Sarpashirsha hands crossed.", math: ["Twisting Pattern: Simulates a mathematically interwoven helix.", "Spiral Geometry: Reflects the coil sequence of a serpent."], nonMath: false },
    { name: "Khatwa", image: "images/pdf_extract/samyutha_p22_1.jpeg", placement: "Two Chatura hands placed facing upwards.", math: ["Linear Structure: Creates a rigid, flat, table-like geometric plane.", "Symmetrical Placement: Four corners perfectly aligned like a grid."], nonMath: false },
    { name: "Bherunda", image: "images/pdf_extract/samyutha_p23_1.jpeg", placement: "Two Kapittha hands joined at wrists.", math: ["Dual Symmetry: Two distinct points expanding outward from a central origin.", "Mirror Imaging: Exact reflection along a shared central vertex."], nonMath: false },
    { name: "Avahiththa", image: "images/pdf_extract/samyutha_p24_1.jpeg", placement: "Two Alapadma hands held crossed on chest.", math: ["Balanced Positioning: Radial blooms intersected and balanced over the heart.", "Spatial Harmony: Perfect geometric distribution of weight and form."], nonMath: false }
];

const dancingEquations = [
    { title: "Linear Functions", desc: "Eye following hand movements forming linear tracks. <strong>Where to see it:</strong> Seen in 'Drishti Bheda' (eye movements) when the dancer's gaze follows the Pataka hand moving horizontally across the chest, tracking a perfect linear path.", equation: "y = mx + c", symbol: "↗" },
    { title: "Circle", desc: "Circular wrist rotations forming continuous geometric circles. <strong>Where to see it:</strong> Seen in 'Alapadma' wrist rotations and 'Bhramari' (spins), where the hand or body rotates around a fixed central point at a constant radius.", equation: "x² + y² = r²", symbol: "◯" },
    { title: "Sine Waves", desc: "Smooth side-to-side neck movements resemble harmonic oscillation. <strong>Where to see it:</strong> Vividly observed in 'Attami' (horizontal neck movements) where the head glides side to side over time, perfectly mapping to a sine wave frequency.", equation: "y = sin(x)", symbol: "∿" },
    { title: "Parabolic Motion", desc: "Dance jumps following gravity-bound parabolic paths. <strong>Where to see it:</strong> Seen in 'Utplavana' (leaps). When a dancer jumps across the stage, their center of gravity follows a perfect mathematical parabola before returning to the ground.", equation: "y = ax² + bx + c", symbol: "∩" },
    { title: "Reflection Symmetry", desc: "Symmetrical mudras showing perfect mirror reflection. <strong>Where to see it:</strong> Seen when the dancer holds the 'Anjali' mudra at the center of the chest. If a vertical line is drawn down the dancer's body, the left side perfectly mirrors the right.", equation: "f(x) = f(-x)", symbol: "◫" },
    { title: "Angular Rotation", desc: "Spins demonstrating angular velocity and momentum. <strong>Where to see it:</strong> Seen during fast 'Chakkars' (spins). The dancer pulls their arms inward to decrease their radius, which mathematically increases their rotational speed due to conservation of angular momentum.", equation: "ω = dθ/dt", symbol: "↻" },
    { title: "Arithmetic Sequences", desc: "Rhythmic footwork representing predictable, mathematically spaced sequences. <strong>Where to see it:</strong> Seen in 'Jathis' (footwork patterns). The dancer strikes the floor in sequences of 3, 4, 5, 7, or 9 beats, calculating complex arithmetic fractions to arrive precisely on the final 'Sam' (first beat).", equation: "a_n = a_1 + (n-1)d", symbol: "1,2,3.." },
    { title: "Coordinate Geometry", desc: "Stage formations assigning dancers to specific spatial coordinates. <strong>Where to see it:</strong> Seen in group choreographies (like 'Tarangam'). The stage acts as an X-Y plane, and dancers move to precise (x,y) coordinates to form triangles, diagonals, and circles.", equation: "(x, y, z)", symbol: "⊞" },
    { title: "Modular Arithmetic", desc: "Rhythm cycles repeating over a set number of beats. <strong>Where to see it:</strong> Seen in 'Tala' (rhythm system). For example, Adi Tala is an 8-beat cycle. Beat 9 is mathematically treated as Beat 1 (9 mod 8 = 1), similar to how a clock works.", equation: "a ≡ b (mod n)", symbol: "⊕" },
    { title: "Wave Functions", desc: "Energetic choreography representing overlapping frequencies. <strong>Where to see it:</strong> Seen when multiple dancers execute ripples with their arms or torso sequentially, mimicking the constructive and destructive interference of physical wave functions.", equation: "Ψ(x,t)", symbol: "≈" }
];

const fusionSubjects = [
    { name: "History", content: "History forms the foundation of Kuchipudi dance as it reflects the traditions and cultural heritage of India. Originating in the village of Kuchipudi in Andhra Pradesh, it preserves the identity and values of ancient kingdoms and saintly traditions. Through dance, history is creatively presented to modern audiences." },
    { name: "Sanskrit", content: "Sanskrit is the linguistic soul of Kuchipudi. The classical slokas, mudra names, and theoretical treatises (like Natya Shastra) are all in Sanskrit, bridging linguistics and expressive performance art." },
    { name: "Biology", content: "Kuchipudi involves intricate body movement, precise muscle coordination, breath control, and stamina. Understanding the biomechanics of the body helps dancers maintain posture and avoid injury while executing complex footwork." },
    { name: "Physics", content: "Concepts of balance, center of gravity, momentum, and angular velocity are heavily utilized during spins, jumps, and maintaining complex postures against gravity." },
    { name: "Literature", content: "Kuchipudi brings ancient literature to life. Poems, epics like the Ramayana and Mahabharata, and poetic compositions are visually translated through Abhinaya (expression)." },
    { name: "Music", content: "The inseparable bond between dance and Carnatic music involves understanding pitch (Shruti), rhythm (Tala), and melody (Raga). The dancer becomes a visual representation of the musical notes." },
    { name: "Psychology", content: "The concept of 'Rasa' and 'Bhava' directly deals with human psychology. Dancers evoke specific emotional responses (Navarasas) in the audience through empathetic facial expressions." },
    { name: "Spirituality", content: "Kuchipudi is inherently devotional. It acts as a medium for self-realization and connecting with the divine, transforming a physical performance into a spiritual offering." },
    { name: "Cultural Studies", content: "It is a living artifact of Indian culture, showcasing traditional attire, jewelry, societal norms, and philosophical beliefs passed down through generations." }
];
